### ISSUE TITLE
Two Issues and a Suggestion

### ISSUE THREAD

**Issue by Caramel146** [Tuttu/StellarisAssets#6]
Hey! First I want to say thanks a lot for your Stellaris Assets tool, it's very handy and I appreciate it.
Two small issues I have encountered:
1. It says "Simply use the menu at the top to navigate between the sections.", but there doesn't appear to be any way to scroll sideways on the top bar. The only way I've found to access Traits now that the Specimen section has been added is to use tab to rotate through links on the page.
2. The way that long keys extend themselves when you hover over them leads to jittery line rearrangements. This is often a tad inconvenient, and for an example of a specific case where it's more troublesome, the Crystalline Entity Voidlure icon/key is nigh-impossible to copy, because hovering over it moves it to the line above, and moving to its new location causes it to jump back!
Also a suggestion - no pressure of course - perhaps a page for ship component icons could be added?
Thanks again!

**Comment by Tuttu** [comment]
Hey!

Thanks for your feedback, I appreciate. :) 

1. The menu *should* be responsive. I will look into it to check what's wrong. In the meantime, can you send me a screenshot of what you get please? That would help me find what's wrong. 
2. You can click on the picture rather than on the text itself. Does that help while I try to find a good solution to that issue? 

Good suggestion. In fact, adding ship components is in the pipeline. It should help quite a lot. ^^

**Comment by Tuttu** [comment]
Hello @Caramel146 !

Good news. With the latest update that's now live, I have fixed the menu issue. It should now display all the menu items, no matter the screen size. When the screen becomes to tiny, the menu switches to a toggle button instead. 

I have also added Ship Parts to the site. Only thing left is to find how to fix the issue you mentioned with the extending keys.

**Comment by Caramel146** [comment]
Hey!
I see the ship parts and the menu works now, very nice!
I've attached images showing the extending keys issue if they help. Unfortunately using snipping tool removes the mouse cursor, so to describe, in the first image I'm hovering over the starbase trading hub, and in the second image I've moved the mouse down to where the crystalline voidlure was, but the cutholoid voidlure is there. (I found a workaround with a bit of fiddling with the tab window, but I hope this helps you fix it for the future!).
![image](https://github.com/user-attachments/assets/3d762ab7-e655-42cb-9f84-5a1175c6855b)
![image](https://github.com/user-attachments/assets/b62cba37-8d0b-4889-90d9-7d7f200fb9f6)

**Comment by Tuttu** [comment]
Hey!
Thanks for the explanations and the screenshots. :) 
Can you also tell me what's your screen resolution please? That will help me a lot to reproduce that behavior which will in turn help solve it.

**Comment by Tuttu** [comment]
Hi again @Caramel146 ,

After quite some loaded weeks, I have some free time to work on this again. Any chance you can tell me the screen resolution you use when getting that issue?

**Comment by Tuttu** [comment]
Hello, 

I found a way to fix that issue. Now, when you hover over an element, if the text overflows it will push the next line a bit down instead. It's way more usable. Thanks for pointing the issue to me.
